/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p24;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Jahir Gaona
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        this.getContentPane().setBackground(Color.CYAN);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbm = new javax.swing.JRadioButton();
        rbS = new javax.swing.JRadioButton();
        lblRH = new javax.swing.JLabel();
        txtRH = new javax.swing.JTextField();
        lblkg = new javax.swing.JLabel();
        txtkg = new javax.swing.JTextField();
        lblG = new javax.swing.JLabel();
        txtG = new javax.swing.JTextField();
        lblM = new javax.swing.JLabel();
        rbkgagrs = new javax.swing.JRadioButton();
        txtRM = new javax.swing.JTextField();
        rbgrsakg = new javax.swing.JRadioButton();
        rbM = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        txtM = new javax.swing.JTextField();
        lblRM = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        txtH = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbm.setForeground(new java.awt.Color(255, 0, 0));
        rbm.setText("minutos");
        rbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmActionPerformed(evt);
            }
        });

        rbS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbS.setForeground(new java.awt.Color(255, 0, 0));
        rbS.setText("segundos");
        rbS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSActionPerformed(evt);
            }
        });

        lblRH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRH.setForeground(new java.awt.Color(255, 0, 0));
        lblRH.setText("Resultado");

        txtRH.setForeground(new java.awt.Color(255, 0, 0));

        lblkg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblkg.setForeground(new java.awt.Color(255, 0, 0));
        lblkg.setText("Kilogramos");

        txtkg.setForeground(new java.awt.Color(255, 0, 0));

        lblG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblG.setForeground(new java.awt.Color(255, 0, 0));
        lblG.setText("Gramos");

        txtG.setForeground(new java.awt.Color(255, 0, 0));

        lblM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblM.setForeground(new java.awt.Color(255, 0, 0));
        lblM.setText("metros");

        rbkgagrs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbkgagrs.setForeground(new java.awt.Color(255, 0, 0));
        rbkgagrs.setText("KG---------->GRS");
        rbkgagrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbkgagrsActionPerformed(evt);
            }
        });

        txtRM.setForeground(new java.awt.Color(255, 0, 0));

        rbgrsakg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbgrsakg.setForeground(new java.awt.Color(255, 0, 0));
        rbgrsakg.setText("KG<-----------GRS");
        rbgrsakg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbgrsakgActionPerformed(evt);
            }
        });

        rbM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbM.setForeground(new java.awt.Color(255, 0, 0));
        rbM.setText("milimetros");
        rbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMActionPerformed(evt);
            }
        });

        rbC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbC.setForeground(new java.awt.Color(255, 0, 0));
        rbC.setText("centimetros");
        rbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCActionPerformed(evt);
            }
        });

        txtM.setForeground(new java.awt.Color(255, 0, 0));

        lblRM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRM.setForeground(new java.awt.Color(255, 0, 0));
        lblRM.setText("Resultado");

        lblH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblH.setForeground(new java.awt.Color(255, 0, 0));
        lblH.setText("Horas");

        txtH.setForeground(new java.awt.Color(255, 0, 0));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 255, 0));
        lblTitulo.setText("CONVERSIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkg))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbkgagrs)
                            .addComponent(rbgrsakg)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblH)
                            .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbm)
                            .addComponent(rbS)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblM)
                            .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbM)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbC)
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtRM, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblRH))
                                    .addComponent(lblG)
                                    .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblTitulo)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblM)
                    .addComponent(rbM)
                    .addComponent(lblRM))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbC)
                        .addComponent(txtRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblH)
                            .addComponent(rbm)))
                    .addComponent(lblRH))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblG)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbkgagrs)
                            .addComponent(lblkg))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbgrsakg)
                    .addComponent(txtkg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmActionPerformed
        rbm.setSelected(true);
        rbS.setSelected(false);
        try{
            double minutos =Double.parseDouble(txtH.getText());
            txtRH.setText(String.valueOf(minutos* 60));
            txtH.setText("");}
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error debes ingresar un numero");
        }
    }//GEN-LAST:event_rbmActionPerformed

    private void rbSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSActionPerformed
        rbm.setSelected(false);
        rbS.setSelected(true);
        try{
            double segundos =Double.parseDouble(txtH.getText());
            txtRH.setText(String.valueOf(segundos * 3600));
            txtH.setText("");}
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error debes ingresar un numero");
        }
    }//GEN-LAST:event_rbSActionPerformed

    private void rbkgagrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbkgagrsActionPerformed
        rbkgagrs.setSelected(false);
        rbgrsakg.setSelected(true);
        try{
            double kilogramos =Double.parseDouble(txtkg.getText());
            txtG.setText(String.valueOf(kilogramos*1000));
            txtkg.setEnabled(true);
            txtkg.setText("");}
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error debes ingresar un numero");
        }
    }//GEN-LAST:event_rbkgagrsActionPerformed

    private void rbgrsakgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbgrsakgActionPerformed
        rbkgagrs.setSelected(true);
        rbgrsakg.setSelected(false);

        try{
            double gramos =Double.parseDouble(txtG.getText());
            txtkg.setText(String.valueOf(gramos * 0.001));
            txtkg.setEnabled(true);
            txtG.setText("");}
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error debes ingresar un numero");
        }
    }//GEN-LAST:event_rbgrsakgActionPerformed

    private void rbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMActionPerformed
        rbM.setSelected(true);
        rbC.setSelected(false);
        try{
            double milimetros =Double.parseDouble(txtM.getText());
            txtRM.setText(String.valueOf(milimetros*1000));
            txtM.setText("");}
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error debes ingresar un numero");
        }
    }//GEN-LAST:event_rbMActionPerformed

    private void rbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCActionPerformed
        rbM.setSelected(false);
        rbC.setSelected(true);
        try{
            double centimetro =Double.parseDouble(txtM.getText());
            txtRM.setText(String.valueOf(centimetro*100));
            txtM.setText("");}
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error debes ingresar un numero");
        }
    }//GEN-LAST:event_rbCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblRH;
    private javax.swing.JLabel lblRM;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblkg;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JRadioButton rbS;
    private javax.swing.JRadioButton rbgrsakg;
    private javax.swing.JRadioButton rbkgagrs;
    private javax.swing.JRadioButton rbm;
    private javax.swing.JTextField txtG;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtRH;
    private javax.swing.JTextField txtRM;
    private javax.swing.JTextField txtkg;
    // End of variables declaration//GEN-END:variables
}
